package finance

import "github.com/gofiber/fiber/v2"

func RegisterRoutes(router fiber.Router, handler *Handler) {
	router.Get("/finance/summary", handler.FinanceSummary)
	router.Get("/finance/bootstrap", handler.FinanceBootstrap)
	router.Get("/finance/categories", handler.Categories)
	router.Get("/finance/quick-exp-categories", handler.QuickExpenseCategories)
	router.Put("/finance/quick-exp-categories", handler.UpdateQuickExpenseCategories)

	adminFinance := router.Group("/admin/finance")
	adminCategories := adminFinance.Group("/categories")
	adminCategories.Post("", handler.CreateCategory)
	adminCategories.Put("/:id", handler.UpdateCategory)

	accounts := router.Group("/accounts")
	accounts.Get("", handler.Accounts)
	accounts.Post("", handler.CreateAccount)
	accounts.Get("/:id", handler.GetAccount)
	accounts.Get("/:id/transactions", handler.AccountTransactions)
	accounts.Get("/:id/balance-history", handler.AccountBalanceHistory)
	accounts.Put("/:id", handler.UpdateAccount)
	accounts.Patch("/:id", handler.PatchAccount)
	accounts.Delete("/:id", handler.DeleteAccount)

	transactions := router.Group("/transactions")
	transactions.Get("", handler.Transactions)
	transactions.Post("", handler.CreateTransaction)
	transactions.Post("/transfer", handler.CreateTransfer)
	transactions.Post("/bulk", handler.CreateTransactionsBulk)
	transactions.Get("/:id", handler.GetTransaction)
	transactions.Put("/:id", handler.UpdateTransaction)
	transactions.Patch("/:id", handler.PatchTransaction)
	transactions.Delete("/:id", handler.DeleteTransaction)

	budgets := router.Group("/budgets")
	budgets.Get("", handler.Budgets)
	budgets.Post("", handler.CreateBudget)
	budgets.Get("/:id", handler.GetBudget)
	budgets.Get("/:id/transactions", handler.BudgetTransactions)
	budgets.Get("/:id/spending", handler.BudgetSpending)
	budgets.Post("/:id/add-value", handler.AddBudgetValue)
	budgets.Post("/:id/recalculate", handler.RecalculateBudget)
	budgets.Put("/:id", handler.UpdateBudget)
	budgets.Patch("/:id", handler.PatchBudget)
	budgets.Delete("/:id", handler.DeleteBudget)

	debts := router.Group("/debts")
	debts.Get("", handler.Debts)
	debts.Post("", handler.CreateDebt)
	debts.Get("/:id", handler.GetDebt)
	debts.Post("/:id/repay", handler.RepayDebt)
	debts.Post("/:id/add-value", handler.AddDebtValue)
	debts.Get("/:id/payments", handler.ListDebtPayments)
	debts.Post("/:id/payments", handler.CreateDebtPayment)
	debts.Patch("/:id/payments/:paymentId", handler.UpdateDebtPayment)
	debts.Delete("/:id/payments/:paymentId", handler.DeleteDebtPayment)
	debts.Post("/:id/settle", handler.SettleDebt)
	debts.Post("/:id/extend", handler.ExtendDebt)
	debts.Put("/:id", handler.UpdateDebt)
	debts.Patch("/:id", handler.PatchDebt)
	debts.Delete("/:id", handler.DeleteDebt)

	counterparties := router.Group("/counterparties")
	counterparties.Get("", handler.Counterparties)
	counterparties.Post("", handler.CreateCounterparty)
	counterparties.Get("/:id", handler.GetCounterparty)
	counterparties.Patch("/:id", handler.PatchCounterparty)
	counterparties.Delete("/:id", handler.DeleteCounterparty)
	counterparties.Get("/:id/debts", handler.CounterpartyDebts)
	counterparties.Get("/:id/transactions", handler.CounterpartyTransactions)

	fx := router.Group("/fx")
	fx.Get("/rates", handler.GetFXRates)
	fx.Post("/rates/manual", handler.CreateFXRate)
	fx.Get("/supported-currencies", handler.SupportedCurrencies)
}
